name: hw3_3dgs_aigc
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - pillow
  - opencv
  - scikit-image
  - scikit-learn
  - imageio
  - imageio-ffmpeg
  - ffmpeg
  - tqdm
  - rich
  - networkx
  - trimesh
  - open3d
  - pydantic
  - jinja2
  - pytorch=2.3.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cudatoolkit
  - cmake
  - ninja
  - git
  - pip:
      - lpips
      - plyfile
      - omegaconf
      - hydra-core
      - lightning
      - transformers
      - diffusers
      - accelerate
      - xformers
      - einops
      - huggingface-hub
      - sentencepiece
      - safetensors
      - gradio
      - nerfacc
      - pycolmap
      - rembg
      - objaverse
      - trimesh[easy]
